name: rsbot
channels:
  - anaconda
  - jmcmurray
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - comtypes=1.1.7=py36_1000
  - freetype=2.10.0=h5db478b_0
  - hdf5=1.8.20=hac2f561_1
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.3=203
  - jpeg=9c=hfa6e2cd_1001
  - json=0.1.1=0
  - libopencv=3.4.2=h20b85fd_0
  - libpng=1.6.36=h7602738_1000
  - libtiff=4.0.10=h36446d0_1001
  - mkl=2019.3=203
  - mkl_fft=1.0.10=py36h14836fe_0
  - mkl_random=1.0.2=py36h343c172_0
  - numpy=1.16.2=py36h19fb1c0_0
  - numpy-base=1.16.2=py36hc3f5095_0
  - olefile=0.46=py_0
  - opencv=3.4.2=py36h40b0b35_0
  - openssl=1.1.1b=hfa6e2cd_2
  - pillow=5.4.1=py36hdc69c19_0
  - pip=19.0.3=py36_0
  - py-opencv=3.4.2=py36hc319ecb_0
  - pyautogui=0.9.42=py36_0
  - pymsgbox=1.0.6=py_0
  - pyscreeze=0.1.19=py_0
  - python=3.6.8=h9f7ef89_7
  - pytweening=1.0.3=py_0
  - pywin32=224=py36hfa6e2cd_1000
  - pywinauto=0.6.6=py36_0
  - qutil=3.2.1=6
  - scipy=1.2.1=py36h29ff71c_0
  - setuptools=27.2.0=py36_1
  - six=1.12.0=py36_1000
  - sqlite=3.27.2=he774522_0
  - tk=8.6.9=hfa6e2cd_1000
  - vc=14.1=h21ff451_3
  - vs2015_runtime=15.5.2=3
  - wheel=0.33.1=py36_0
  - zlib=1.2.11=h2fa13f4_1004
prefix: C:\Anaconda3\envs\rsbot
